if (COMP_NAME STREQUAL mpi-serial)
  string(APPEND CFLAGS " -std=gnu89")
else()
  string(APPEND CFLAGS " -std=gnu99")
endif()
if (compile_threaded)
  string(APPEND CFLAGS " -fopenmp")
endif()
if (DEBUG)
  string(APPEND CFLAGS " -g -Wall -Og -fbacktrace -ffpe-trap=invalid,zero,overflow -fcheck=bounds")
endif()
if (NOT DEBUG)
  string(APPEND CFLAGS " -O")
endif()
string(APPEND CPPDEFS " -DFORTRANUNDERSCORE -DNO_R16 -DCPRGNU")
set(CXX_LINKER "FORTRAN")
set(FC_AUTO_R8 "-fdefault-real-8 -fdefault-double-8")
string(APPEND FFLAGS " -fconvert=big-endian -ffree-line-length-none -ffixed-line-length-none")
if (compile_threaded)
  string(APPEND FFLAGS " -fopenmp")
endif()
if (DEBUG)
  string(APPEND FFLAGS " -g -Wall -Og -fbacktrace -ffpe-trap=zero,overflow -fcheck=bounds")
endif()
if (NOT DEBUG)
  string(APPEND FFLAGS " -O")
endif()
set(FFLAGS_NOOPT "-O0")
set(FIXEDFLAGS "-ffixed-form")
set(FREEFLAGS "-ffree-form")
set(HAS_F2008_CONTIGUOUS "FALSE")
if (compile_threaded)
  string(APPEND LDFLAGS " -fopenmp")
endif()
set(MPICC "cc")
set(MPICXX "CC")
set(MPIFC "ftn")
set(SCC "cc")
set(SCXX "CC")
set(SFC "ftn")
set(NETCDF_PATH "$ENV{NETCDF_DIR}")
set(PNETCDF_PATH "$ENV{PNETCDF_DIR}")
set(SLIBS " -lnetcdff -lnetcdf")
set(ESMF_LIBDIR "/users/jbuzan/esmf_jon/ESMF/lib/libO/Linux.gfortran.64.mpich.default/")
set(SUPPORTS_CXX "TRUE")

message("C compiler version is ${CMAKE_C_COMPILER_VERSION}")
message("Fortran compiler version is ${CMAKE_Fortran_COMPILER_VERSION}")
if (CMAKE_Fortran_COMPILER_VERSION VERSION_GREATER_EQUAL 10)
  string(APPEND FFLAGS " -fallow-argument-mismatch  -fallow-invalid-boz ")
endif()
