if (compile_threaded)
  string(APPEND CFLAGS " -qopenmp")
endif()
if (NOT DEBUG)
  string(APPEND CFLAGS " -O2")
endif()
if (DEBUG)
  string(APPEND CFLAGS " -g -traceback -O0 -check all -fpe0 -ftrapuv -init=snan,arrays")
endif()
if (COMP_NAME STREQUAL mpi-serial)
  string(APPEND CFLAGS " -std=c89 ")
endif()	
string(APPEND LDFLAGS " -L/opt/cray/libfabric/1.15.2.0/lib64")
string(APPEND CFLAGS " -no-fma")
string(APPEND CPPDEFS " -DFORTRANUNDERSCORE -DCPRINTEL")
string(APPEND CXX_LDFLAGS " -cxxlib")
set(CXX_LINKER "FORTRAN")
set(FC_AUTO_R8 "-r8")
string(APPEND FFLAGS " -qno-opt-dynamic-align  -convert big_endian -assume byterecl -ftz -traceback -assume realloc_lhs -fp-model source")
if (compile_threaded)
  string(APPEND FFLAGS " -qopenmp")
endif()
set(NETCDF_PATH "$ENV{NETCDF_DIR}")
set(PNETCDF_PATH "$ENV{PNETCDF_DIR}")
set(SLIBS " -lnetcdff -lnetcdf -lfabric")
set(ESMF_LIBDIR "/users/jbuzan/esmf_jon/ESMF_INTEL/lib/libO/Linux.intel.64.mpich.default/")
set(MPICC "cc")
set(MPICXX "CC")
set(MPIFC "ftn")
set(SCC "cc")
set(SCXX "CC")
set(SFC "ftn")
if (MPILIB STREQUAL mpich)
  string(APPEND SLIBS " -mkl=cluster")
endif()
set(SUPPORTS_CXX "TRUE")
string(APPEND FFLAGS " -no-fma")
set(FIXEDFLAGS "-fixed")
set(FREEFLAGS "-free")
set(FFLAGS_NOOPT "-O0")

